define([], function() {
    var FooterView = {
       "views":{
       	    "commentFoot":{
       	    	"template":"text!commonTemplate/foot/commentFoot.html",
       	    	"func":undefined,
       	    },
    	   "oneButtonFoot":{
    		   "template":"text!commonTemplate/foot/oneButtonFoot.html",
    		   "func":{
    			   "button":undefined
    		   },
    	   
    	   },
    	   "confirmOrder":{
    		   "template":"text!commonTemplate/foot/confirmOrder.html",
    		   "func":{
    			   "button":undefined
    		   },
    		   
    	   },
    	   "projectDetsFoot":{
    		   "template":"text!commonTemplate/foot/projectDetsFoot.html",
    		   "func":{
    			   "exchange":undefined,
    			   "buyImmediately":undefined,
                   "addShoppingCart":undefined,
    		   },
    		   "data":{}
    	   },
    	   //支持订单-回报项目
    	   "supportOrderReFoot":{
    		   "template":"text!commonTemplate/foot/supportOrderReFoot.html",
    		   "func":{
    			   "button":undefined
    		   },
    		   "data":{}
    	   },
    	   //发送消息
    	   "sendButton":{
    		   "template":"text!commonTemplate/foot/sendButton.html",
    	   },
    	   "investFoot":{
    		   "template":"text!commonTemplate/foot/investFoot.html",
    	   },
    	   "mainFoot":{
    		   "template":"text!commonTemplate/foot/mainFootNew.html",
    		   "data":{
    			   "hash":window.location.hash.substring(1)
    		   },
    		   "func":{
    			   "index":function($dom){
       					DMJS.router.navigate("index/index/index",true);
                    },
                    "start":function(){
                            DMJS.router.navigate("start/start/start",true);
                    },
                    "trends":function(){
                            DMJS.router.navigate("trends/trends/trends",true);
                    },
                    "userInfo":function(){
                    	DMJS.router.navigate("user/personal/userCenter",true);
                    }
    		   },
    		   "onLoad":function($dom,hash){
    			   $dom.find("input").each(function(){
    			   	   $(this).parent().removeClass("fn-c-blue");
    				   if(hash==$(this).attr("activeHash")){
    					   $(this).attr("checked",true);
    					   $(this).parent().addClass("fn-c-blue");
    				   }else{
    					   $(this).removeAttr("checked");
    				   }
    			   });
    		   }
    	   }
       }
    };
    return FooterView;
});
